### ISSUE TITLE
how to build Arpack in julia

### ISSUE THREAD

**Issue by ShuaiNIEgithub** [arzwa/Whale.jl#1]
When I tried installing whale.pj on v1.1.1 and saw this error:

 Building Arpack → `~/.julia/packages/Arpack/cu5By/deps/build.log`
┌ **Error**: Error building `Arpack`:
│ [ Info: Downloading https://github.com/JuliaLinearAlgebra/ArpackBuilder/releases/download/v3.5.0-3/Arpack.v3.5.0-3.x86_64-linux-gnu-gcc7.tar.gz
to /home/nieshuai/.julia/packages/Arpack/cu5By/deps/usr/downloads/Arpack.v3.5.0-3.x86_64-linux-gnu-gcc7.tar.gz...
│ ERROR: LoadError: LibraryProduct(nothing, ["libarpack"], :libarpack, "Prefix(/home/nieshuai/.julia/packages/Arpack/cu5By/deps/usr)") is not satisfied, cannot generate deps.jl!
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] #write_deps_file#152(::Bool, ::Function, ::String, ::Array{LibraryProduct,1}) at /home/nieshuai/.julia/packages/BinaryProvider/TcAwt/src/Products.jl:414
│  [3] (::getfield(BinaryProvider, Symbol("#kw##write_deps_file")))(::NamedTuple{(:verbose,),Tuple{Bool}}, ::typeof(write_deps_file), ::String, ::Array{LibraryProduct,1}) at ./none:0
│  [4] top-level scope at none:0
│  [5] include at ./boot.jl:326 [inlined]
│  [6] include_relative(::Module, ::String) at ./loading.jl:1038
│  [7] include(::Module, ::String) at ./sysimg.jl:29
│  [8] include(::String) at ./client.jl:403
│  [9] top-level scope at none:0
│ in expression starting at /home/nieshuai/.julia/packages/Arpack/cu5By/deps/build.jl:74
[21:15:25] ######################################################################## 100.0%

**the info of julia:**
 versioninfo()
Julia Version 1.1.1
Platform Info:
  OS: Linux (x86_64-conda_cos6-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2630 0 @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, sandybridge)

To solve this problem, I used three methods:
1. I used the official binaries from julialang.org, but the version of my apt-get is too low and the upgrade failed.
2. I see https://github.com/JuliaLinearAlgebra/Arpack.jl/issues/5. however, I couldn't find an effective way.
3. Ultimately, I tried the solution suggested by the third answer at https://www.oipapio.com/question-11699618. But I can't find libopenblas64_.so.0 in my system.

Could you give me some advice on how to solve it?

**Comment by arzwa** [comment]
I'm not sure what the problem is exactly, but maybe you can try with LTS version of julia (Long-term support (LTS) release: v1.0.4, whcih you can find [here](https://julialang.org/downloads/))?

**Comment by ShuaiNIEgithub** [comment]
Yes, I will try that. Thank you so much!
